title: おひさまの森保育園
description: >-
  おひさまの森保育園は、子ども一人ひとりの気持ちを大切にし、のびのびと過ごせる保育環境を提供しています。
  自然や遊びを通して心と体の成長を育みます。安心・安全な保育を心がけ、子どもたちが笑顔で過ごせる場所を目指します。

lang: ja
timezone: Asia/Tokyo

url: "https://mika1119.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/sun_forest_school" # the subpath of your site, e.g. /blog

plugins:
  - jekyll-feed

header_pages:
  - index.md